
targets = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-url = "https://github.com/rustsec/advisory-db"
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"
ignore = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
wildcards = "allow"


[licenses]
unlicensed = "deny"
allow = ["MIT"]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = []


[licenses.private]
ignore = true


[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
